# Generated by Django 5.0.6 on 2024-05-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='제목')),
                ('description', models.TextField(verbose_name='설명')),
                ('urgency', models.IntegerField(choices=[(1, '긴급'), (2, '긴급하지 않음')], verbose_name='긴급도')),
                ('importance', models.IntegerField(choices=[(1, '중요'), (2, '중요하지 않음')], verbose_name='중요도')),
                ('category', models.IntegerField(choices=[(1, '지금 할 일'), (2, '나중에 할 일'), (3, '위임'), (4, '삭제')], default=1, verbose_name='카테고리')),
            ],
        ),
    ]
