# Generated by Django 5.0.6 on 2024-05-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.IntegerField(choices=[(1, '지금 하기'), (2, '나중에 하기'), (3, '위임하기'), (4, '삭제하기')], default=4, verbose_name='카테고리'),
        ),
    ]
